spring.application.name=micro-pacientes
server.port=8082
logging.level.root=INFO
logging.level.org.hibernate=DEBUG
logging.level.org.springframework=DEBUG

spring.datasource.url=jdbc:oracle:thin:@ctagtsp6ga68lfba_high?TNS_ADMIN=C:/Users/mar_x/Downloads/Wallet_CTAGTSP6GA68LFBA
spring.datasource.username=ADMIN
spring.datasource.password=Bayonetta2024
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size= 10
spring.datasource.hikari.connection-timeout= 30000
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/145f8758-681d-4413-9137-2973073f86e2/discovery/v2.0/keys
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/da33d9d5-d2db-47f9-9d73-996ec0dd60d2/discovery/v2.0/keys
#https://login.microsoftonline.com/da33d9d5-d2db-47f9-9d73-996ec0dd60d2/v2.0

